###
POST http://localhost:8080/api/users/login
Accept: application/json
Accept-Language: zh-CN
Content-Type: application/json

{
  "data": {
    "username": "e1@neusoft.com",
    "password": "123ABCabc"
  }
}

> {%
    client.global.set('token', response.body['data']['token'])
%}

###
GET http://localhost:8080/api/vocations
Accept: application/json
Accept-Language: zh-CN
Authorization: {{token}}

###
POST http://localhost:8080/api/vocations/apply
Accept: application/json
Accept-Language: zh-CN
Authorization: {{token}}
Content-Type: application/json

{
  "data": {
    "type": 2,
    "start": "2025-01-10",
    "end": "2025-02-10"
  }
}

###
GET http://localhost:8080/api/vocations/apply
Accept: application/json
Accept-Language: zh-CN
Authorization: {{token}}
Content-Type: application/json

###
PUT http://localhost:8080/api/vocations/apply
Accept: application/json
Accept-Language: zh-CN
Authorization: {{token}}
Content-Type: application/json

{
  "data": {
    "id": 1,
    "agree": true
  }
}