mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehr
  jackson:
    default-property-inclusion: non_null